### ISSUE TITLE
Chapter 7 build errors

### ISSUE THREAD

**Issue by harperjohn** [PacktPublishing/Web-Development-with-Blazor#1]
Chapter 7 will not build for me... I looked at if for quite a while this afternoon and I could not see/find the problem

========

![chapter7errors](https://user-images.githubusercontent.com/10133260/133173722-a6ef475d-4c22-4323-b1e5-ff2f4b3299f0.PNG)

**Comment by EngstromJimmy** [comment]
There was a package missing from the MyBlog.Data-project.
Thanks for letting me know, I have added it now, please try again.
