### ISSUE TITLE
Blazor in dotnet 6.0

### ISSUE THREAD

**Issue by dan508** [PacktPublishing/Web-Development-with-Blazor#10]
Is there any info on the changes to dotnet6.0? dotnet 6.0 has removed the startup file and states that everything should go int the program.cs file instead, however I can't see how to add the code  (as per chapter 'adding the dbcontect to blazor') to the program.cs file.

**Comment by EngstromJimmy** [comment]
I assume you are talking about the migration?
A simple solution could be to create a component that injects the IDBContextFactory and runs the migration code.
A good practice is to run the migrations from the command but to simplify things during this demo I put the migration at startup.
Hope that helps =)
