### ISSUE TITLE
Chapter 4 - cannot insert blog posts

### ISSUE THREAD

**Issue by jira-zz** [PacktPublishing/Web-Development-with-Blazor#12]
I'm reading chapter 4, but the code to populate the db with fake BlogPosts is not working.
Ends with SQLite Error 19: 'FOREIGN KEY constraint failed'

Stack trace attached

[stacktrace.txt](https://github.com/PacktPublishing/Web-Development-with-Blazor/files/8005705/stacktrace.txt)

**Comment by EngstromJimmy** [comment]
Do you have any Categories in the database? (you shouldn't have at this point)
I downloaded the source from Github and I can't reproduce the problem.
Could you share your code with me?

**Comment by kwang1971** [comment]
Yes，I also can not insert blogposts, seems the category not null constraint.

**Comment by EngstromJimmy** [comment]
@kwang1971 Thanks for the report, did you use that code from GitHub or did you copy it from the book?
Would it be possible for me to get a copy of your code (since I can't reproduce the problem).
You can email it to me at: jimmy@apeoholic.se
Thanks

**Comment by dan508** [comment]
I am having the same issue. (Using SQLServer rather the SQLExpress).
 On page 93 of the but when I debug the application, I press the button and the following appears on my debut output

I have used the book entirely for this, no copy/pasting from the git repo

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_BlogPosts_Categories_CategoryId". The conflict occurred in database "Test", table "dbo.Categories", column 'Id'.
The statement has been terminated.

**Comment by EngstromJimmy** [comment]
@dan508 @kwang1971 @jira-zz  you can try and add a category in the database and make sure you add the category then you create the fake posts.

I would love to hear if you are running into the same problem using the code on GitHub.
Since I can't reproduce the problem with the GitHub code it would help to figure out where the problem might be.
There is obviously something in the book that is wrong, but I can't find it.
