### ISSUE TITLE
No Menu bar in Chapter 5 end solution

### ISSUE THREAD

**Issue by PeterZCLu** [PacktPublishing/Web-Development-with-Blazor#4]
Hi, There, I encounter difficult in getting chapter 6 work from my codebase. so I pull your repo and try to use chapter 5 as starting point to work on chapter 6. to my surprise, Chapter 5 codebase does not have menu bar when I run it. please help

**Comment by EngstromJimmy** [comment]
It seems to be CSS missing in the repo, really strange.
I have added the CSS.
Hopefully, it works as you expect now =)
