### ISSUE TITLE
Chapter 9, Setting up the API

### ISSUE THREAD

**Issue by pmarangoni** [PacktPublishing/Web-Development-with-Blazor#7]
There is a reference to a project that hasn't been created yet in step 5 on page187.

> "Click Add project reference, check the MyBlog.Data.Shared and **MyBlog.Shared** checkboxes, and then click OK."

**MyBlog.Shared** project isn't created until two pages later, under **Moving the components**.

**Comment by EngstromJimmy** [comment]
ah, I see the problem.
Thanks for letting me know.
I have added it to the readme file.
