### ISSUE TITLE
IBlogNotificationService.cs (Chapter 11)

### ISSUE THREAD

**Issue by pmarangoni** [PacktPublishing/Web-Development-with-Blazor#9]
On line 35 in
https://github.com/PacktPublishing/Web-Development-with-Blazor/blob/master/Chapter11/MyBlog/MyBlogWebAssembly/Client/Services/BlazorWebAssemblyBlogNotificationService.cs
you have 
`public event Action<BlogPost> BlogPostChanged;` 
but in the book you have 
`public Action<BlogPost> BlogPostChanged { get; set; }`

Simlarly, in IBlogNotificationService.cs here in GitHub, you have 
`event Action<BlogPost> BlogPostChanged;` 
but in the book it is 
` Action<BlogPost> BlogPostChanged {get; set;}`

**Comment by EngstromJimmy** [comment]
Thanks for letting me know, I have updated the readme file.
It is probably a safe bet to say that the repo contains more recent code (since I do update it if we find any problems).
